### ISSUE TITLE
Validation data

### ISSUE THREAD

**Issue by mboeni** [seungwonpark/melgan#38]
Quick question: where do I get / generate the validation data required (I'm using the LJSpeech set)?

If you can point to other/better training data with the corresponding validation data, also let me know please.

**Comment by seungwonpark** [comment]
I simply split the whole LJ data to 9:1 for train/val.

Seung-won Park
Undergraduate Student
Dept. of Physics and Astronomy & Computer Science Engineering
Seoul National University
yyyyy@snu.ac.kr | http://swpark.me
________________________________

**Comment by mboeni** [comment]
That was quick! Thanks, will do.

**Comment by mboeni** [comment]
Any idea on this issue:

`
λ python trainer.py -c config/config.yaml -n InitialRun
2019-12-14 22:51:36,483 - INFO - Starting new training run.
Validation loop:   0%|                                                                                          | 0/1552 [00:00<?, ?it/s]2019-12-14 22:51:36,492 - INFO - Exiting due to exception: '__getstate__'
Traceback (most recent call last):
  File "D:\dev\melgan\utils\train.py", line 60, in train
    validate(hp, args, model_g, model_d, valloader, writer, step)
  File "D:\dev\melgan\utils\validation.py", line 13, in validate
    for mel, audio in loader:
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\site-packages\tqdm\_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
KeyError: '__getstate__'

mbo@zendo /d/dev/melgan (master)
λ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\mbo\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

?`

**Comment by mboeni** [comment]
Also, if you have any example code for the audio generation, that would be appreciated :)

**Comment by wangqilun** [comment]
@seungwonpark @mboeni Have you solve this error? I encountered the same error.

**Comment by teamimx** [comment]
Nope, not yet...

**Comment by kookiny** [comment]
@seungwonpark 
Anyone knows what the problem was? or solved it?

**Comment by MckinstryJ** [comment]
@seungwonpark Its been awhile since the last comment but has anyone figured out this issue for LJSpeech? Adjusting the batch_size to 1 or 2^n didn't help.
